TOKEN = 'BOT_TOKEN'
DATABASE_NAME = 'DB_NAME'
DATABASE_USER = 'DB_USER'
DATABASE_PASSWORD = 'DB_PWD'
DATABASE_HOST = 'DB_IP'
DATABASE_PORT = '5432'
START = range(1)  # Define your conversation states here
